object Versions {
    const val coreKtx = "1.7.0"
    const val appCompat = "1.6.1"
    const val material = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val jUnitAndroid = "1.1.5"
    const val espressoAndroid = "3.5.1"
    const val hilt = "2.44"
    const val retrofit ="2.9.0"
    const val coreSplashScreen = "1.0.0-beta02"
    const val loggingInterceptor = "4.10.0"
    const val viewModelLifeCycle = "2.5.1"
    const val activityKtx = "1.6.1"
    const val glide = "4.14.2"
    const val room = "2.5.0"
    const val jodaTime = "2.12.1.1"
    const val lottie = "5.2.0"
}